### PR TITLE
🐛 Fix restricting address family when watching for changes

### LINKED ISSUE #5: Glitch with --interface-family=ipv6
I've noticed a glitch using `--interface-family=ipv6`: It can happen that a IPv4 address is used for the update.

I have go-nsupdate running using `--watch`:
~~~
/usr/local/bin/go-nsupdate \
--tsig-algorithm=hmac-sha512 --tsig-name=bims.dyn.bl0rg.net \
--interface=eth0 --interface-family=ipv6 --watch bims.dyn.bl0rg.net
~~~

Among the IPv6 addresses there was once an IPv4 address used for the nsupdate:
~~~
...
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 AddrSet iface=eth0: up 2a02:8109:9e40:3f61:11:32ff:fe23:913f
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 addrs update...                                           
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 update...                                                 
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 update query...                                           
Jun 20 11:19:50 bims go-nsupdate[342693]: 2022/06/20 11:19:50 update answer                                             
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 AddrSet iface=eth0: up 192.168.144.3                      
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 addrs update...                                           
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 update...                                                 
Jun 20 11:20:21 bims go-nsupdate[342693]: 2022/06/20 11:20:21 update query...                                           
Jun 20 11:20:22 bims go-nsupdate[342693]: 2022/06/20 11:20:22 update answer                                             
Jun 20 11:22:04 bims go-nsupdate[342693]: 2022/06/20 11:22:04 AddrSet iface=eth0: up 2a02:8109:9e40:3f61:11:32ff:fe23:913f
...
~~~

@SpComb Any idea how this could happen?

### PR DESCRIPTION
**Pull request by neingeist**
I had a bit of a difficulty with using "netlink/ns" vs go.mod/subs, so this might not be ideal.

Fixes #5.

### CODE REVIEW

**Comment by neingeist** [comment]
Please don't merge yet, I noticed that go-nsupdate "caught" IPv4 changes (DHCP?) every 12 hours on my test machine and I'd like to test this for a day first.

**Review by SpComb — APPROVED** [review]
This fix looks like it should do the right thing :thinking: let me know what your testing looks like - it should be possible to verify this with just `ip addr add/del ...` and not have to wait for DHCP lease updates.

**Comment by SpComb** [comment]
Looks like this needs a rebase or commit to run the new GitHub actions workflow, there doesn't seem to be any way to trigger a new workflow for an existing PR.

**Comment by neingeist** [comment]
> This fix looks like it should do the right thing thinking let me know what your testing looks like - it should be possible to verify this with just `ip addr add/del ...` and not have to wait for DHCP lease updates.

I have a few VMs at home and a dynamic IPv6 prefix, so I run `go-nsupdate --watch --interface-family ipv6` to update AAAA records.

I tested using `ip a a`/`ip a d` for the IPv4 address, and go-nsupdate with this PR is ignoring it, so I think this working fine. I'll rebase to run the workflow!

**Review by SpComb — APPROVED** [review]

**Pull request merged**
